import { NextResponse } from 'next/server';

export const runtime = 'nodejs';
export const maxDuration = 60;

export async function POST(request) {
  // Replace this with the HTTP POST URL generated by your new Flow 3
  const INSIGHTS_FLOW_URL = "YOUR_NEW_FLOW_3_HTTP_URL"; 

  try {
    const body = await request.json();
    const response = await fetch(INSIGHTS_FLOW_URL, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(body),
    });

    const data = await response.json();
    return NextResponse.json(data, { status: 200 });
  } catch (error) {
    return NextResponse.json({ error: 'Analysis failed' }, { status: 500 });
  }
}
